name: 'Prettier, please!'
description: 'Formats your code and documentation with Prettier, if you ask nicely.'
author: 'Reid Draper'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  git-user.name:
    description: Name to use for git commits
    required: false
    default: 'github-actions[bot]'
  git-user.email:
    description: Email to use for git commits
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
runs:
  using: 'node12'
  main: 'dist/index.js'
